/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Type = IDL.Variant({
  'lab' : IDL.Null,
  'library' : IDL.Null,
  'blockA' : IDL.Null,
  'blockB' : IDL.Null,
  'foodCourt' : IDL.Null,
  'parking' : IDL.Null,
});
export const Teacher = IDL.Record({
  'id' : IDL.Text,
  'isOnCampus' : IDL.Bool,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'email' : IDL.Text,
  'locationZone' : IDL.Opt(Type),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Variant({ 'teacher' : IDL.Null, 'student' : IDL.Null }),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerStudent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'registerTeacher' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchTeachersByName' : IDL.Func([IDL.Text], [IDL.Vec(Teacher)], ['query']),
  'setCampusPresence' : IDL.Func([IDL.Bool], [], []),
  'setLocationZone' : IDL.Func([Type], [], []),
  'toggleAvailability' : IDL.Func([IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Type = IDL.Variant({
    'lab' : IDL.Null,
    'library' : IDL.Null,
    'blockA' : IDL.Null,
    'blockB' : IDL.Null,
    'foodCourt' : IDL.Null,
    'parking' : IDL.Null,
  });
  const Teacher = IDL.Record({
    'id' : IDL.Text,
    'isOnCampus' : IDL.Bool,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'email' : IDL.Text,
    'locationZone' : IDL.Opt(Type),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Variant({ 'teacher' : IDL.Null, 'student' : IDL.Null }),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerStudent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'registerTeacher' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchTeachersByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Teacher)],
        ['query'],
      ),
    'setCampusPresence' : IDL.Func([IDL.Bool], [], []),
    'setLocationZone' : IDL.Func([Type], [], []),
    'toggleAvailability' : IDL.Func([IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };